-- Precios de entrega por zona/comuna RM (CLP)
-- Ejecutar en Supabase SQL Editor
-- Idempotente: actualiza si ya existe, inserta si no existe.

insert into price_configs (commune, price, zone)
values
  ('Alhué',               30000, ''),
  ('Buin',                12000, ''),
  ('Calera De Tango',     10000, ''),
  ('Cerrillos',            5000, ''),
  ('Cerro Navia',          4500, ''),
  ('Colina',              10000, ''),
  ('Conchalí',             4500, ''),
  ('Curacaví',            15000, ''),
  ('El Bosque',            6000, ''),
  ('El Monte',            18000, ''),
  ('Estación Central',     4000, ''),
  ('Huechuraba',           4000, ''),
  ('Independencia',        4000, ''),
  ('Isla De Maipo',       20000, ''),
  ('La Cisterna',          4500, ''),
  ('La Florida',           7500, ''),
  ('La Granja',            4500, ''),
  ('La Pintana',           6000, ''),
  ('La Reina',             4000, ''),
  ('Lampa',                5000, ''),
  ('Las Condes',           4000, ''),
  ('Lo Barnechea',         5000, ''),
  ('Lo Espejo',            4500, ''),
  ('Lo Prado',             4000, ''),
  ('Macul',                4500, ''),
  ('Maipú',                5000, ''),
  ('María Pinto',         20000, ''),
  ('Melipilla',           20000, ''),
  ('Ñuñoa',                4000, ''),
  ('Padre Hurtado',       10000, ''),
  ('Paine',               15000, ''),
  ('Pedro Aguirre Cerda',  4500, ''),
  ('Peñaflor',            12000, ''),
  ('Peñalolén',            5000, ''),
  ('Pirque',              10000, ''),
  ('Providencia',          4000, ''),
  ('Pudahuel',             6000, ''),
  ('Puente Alto',          8000, ''),
  ('Quilicura',            5000, ''),
  ('Quinta Normal',        4000, ''),
  ('Recoleta',             4500, ''),
  ('Renca',                5000, ''),
  ('San Bernardo',        10000, ''),
  ('San Joaquín',          4500, ''),
  ('San José De Maipo',   12000, ''),
  ('San Miguel',           4500, ''),
  ('San Pedro',           30000, ''),
  ('San Ramón',            4500, ''),
  ('Santiago',             4500, ''),
  ('Talagante',           15000, ''),
  ('Tiltil',              10000, ''),
  ('Vitacura',             4000, '')
on conflict (commune) do update set
  price      = excluded.price,
  updated_at = now();
