-- Catalogo editable de articulos para el cotizador de fletes/mudanzas.
-- Ejecutar en Supabase SQL Editor. Es idempotente.
-- Mantener sincronizado con client/src/components/InventoryPicker.jsx (CATALOG).

create table if not exists inventory_item_configs (
  id uuid primary key default gen_random_uuid(),
  item_key text not null unique,
  name text not null,
  icon text not null default '📦',
  category text not null default 'Otros',
  volume_m3 numeric not null default 0,
  min_vehicle_type text not null default 'furgon' check (min_vehicle_type in ('furgon', 'camion34', 'camionLargo')),
  required_helpers integer not null default 0,
  is_heavy boolean not null default false,
  is_fragile boolean not null default false,
  is_long boolean not null default false,
  is_tall boolean not null default false,
  active boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table inventory_item_configs add column if not exists is_heavy boolean not null default false;
alter table inventory_item_configs add column if not exists is_fragile boolean not null default false;
alter table inventory_item_configs add column if not exists is_long boolean not null default false;
alter table inventory_item_configs add column if not exists is_tall boolean not null default false;

insert into inventory_item_configs (item_key, name, icon, category, volume_m3, min_vehicle_type, required_helpers, is_heavy, is_fragile, is_long, is_tall, sort_order)
values
-- Dormitorio
('cama1p',      'Cama 1 plaza',        '🛏️', 'Dormitorio', 1.5, 'furgon',   0, false, false, true,  false, 10),
('cama15p',     'Cama 1½ plaza',       '🛏️', 'Dormitorio', 1.8, 'furgon',   0, false, false, true,  false, 20),
('cama2p',      'Cama 2 plazas',       '🛏️', 'Dormitorio', 2.0, 'camion34', 1, true,  false, true,  false, 30),
('camaQueen',   'Cama Queen / King',   '🛏️', 'Dormitorio', 2.8, 'camion34', 1, true,  false, true,  false, 40),
('camarote',    'Camarote / litera',   '🛏️', 'Dormitorio', 2.6, 'camion34', 1, true,  false, false, true,  50),
('colchon',     'Colchón suelto',      '🛌', 'Dormitorio', 1.0, 'furgon',   0, false, false, true,  false, 60),
('closet',      'Clóset / ropero',     '🚪', 'Dormitorio', 2.5, 'camion34', 1, true,  false, false, true,  70),
('comoda',      'Cómoda',              '🗄️', 'Dormitorio', 0.8, 'furgon',   0, false, false, false, false, 80),
('mesaNoche',   'Velador / mesa noche','🪑', 'Dormitorio', 0.3, 'furgon',   0, false, false, false, false, 90),
('tocador',     'Tocador / peinadora', '💄', 'Dormitorio', 0.9, 'furgon',   0, false, true,  false, false, 100),
('espejoPie',   'Espejo de cuerpo',    '🪞', 'Dormitorio', 0.4, 'furgon',   0, false, true,  false, false, 110),
('baul',        'Baúl / arcón',        '🧰', 'Dormitorio', 0.6, 'furgon',   0, false, false, false, false, 120),
-- Living
('sofa1p',      'Sillón 1 cuerpo',     '🛋️', 'Living', 1.2, 'furgon',   0, false, false, false, false, 130),
('sofa2p',      'Sofá 2 plazas',       '🛋️', 'Living', 2.0, 'furgon',   1, true,  false, false, false, 140),
('sofa3p',      'Sofá 3 plazas',       '🛋️', 'Living', 3.2, 'camion34', 1, true,  false, true,  false, 150),
('sofaSecc',    'Sofá seccional / L',  '🛋️', 'Living', 4.5, 'camion34', 2, true,  false, true,  false, 160),
('sofaCama',    'Sofá cama / futón',   '🛋️', 'Living', 3.0, 'camion34', 1, true,  false, false, false, 170),
('sillonRecl',  'Sillón reclinable',   '💺', 'Living', 1.6, 'furgon',   1, true,  false, false, false, 180),
('rackTv',      'Rack / mueble TV',    '📼', 'Living', 1.2, 'furgon',   0, false, false, false, false, 190),
('mesaCentro',  'Mesa de centro',      '🪵', 'Living', 0.6, 'furgon',   0, false, false, false, false, 200),
('tvSmall',     'TV hasta 50"',        '📺', 'Living', 0.3, 'furgon',   0, false, true,  false, false, 210),
('tvLarge',     'TV 55" o más',        '📺', 'Living', 0.6, 'furgon',   0, false, true,  false, false, 220),
('homeTheater', 'Home theater / parlantes', '🔊', 'Living', 0.4, 'furgon', 0, false, true, false, false, 230),
('alfombra',    'Alfombra enrollada',  '🧶', 'Living', 0.4, 'furgon',   0, false, false, true,  false, 240),
('lamparaPie',  'Lámpara de pie',      '💡', 'Living', 0.3, 'furgon',   0, false, true,  false, false, 250),
-- Comedor
('mesaComedor', 'Mesa comedor',        '🍽️', 'Comedor', 1.2, 'furgon',   0, false, false, false, false, 260),
('mesaComedorXl','Mesa comedor 8+',    '🍽️', 'Comedor', 2.2, 'camion34', 1, true,  false, true,  false, 270),
('silla',       'Silla (x1)',          '🪑', 'Comedor', 0.3, 'furgon',   0, false, false, false, false, 280),
('piso',        'Piso / banqueta',     '🪑', 'Comedor', 0.2, 'furgon',   0, false, false, false, false, 290),
('vitrina',     'Vitrina / cristalero','🗃️', 'Comedor', 1.8, 'camion34', 1, true,  true,  false, true,  300),
('aparador',    'Aparador / bufetera', '🪟', 'Comedor', 1.4, 'furgon',   1, true,  false, false, false, 310),
-- Cocina
('nevera',      'Refrigerador',        '🧊', 'Cocina', 1.5, 'camion34', 1, true,  false, false, true,  320),
('neveraSbs',   'Refrigerador side-by-side', '🧊', 'Cocina', 2.2, 'camion34', 2, true, false, false, true, 330),
('freezer',     'Freezer / congeladora','❄️', 'Cocina', 1.2, 'furgon',   1, true,  false, false, false, 340),
('cocina',      'Cocina / horno',      '🍳', 'Cocina', 1.0, 'camion34', 1, true,  false, false, false, 350),
('hornoEmp',    'Horno / encimera empotrable', '🔥', 'Cocina', 0.5, 'furgon', 0, false, false, false, false, 360),
('microondas',  'Microondas',          '📟', 'Cocina', 0.1, 'furgon',   0, false, false, false, false, 370),
('lavavajillas','Lavavajillas',        '🍴', 'Cocina', 0.7, 'furgon',   1, true,  false, false, false, 380),
('muebleCocina','Mueble / repisa de cocina', '🗄️', 'Cocina', 1.0, 'furgon', 0, false, false, false, false, 390),
('menaje',      'Caja de menaje / vajilla', '🍶', 'Cocina', 0.2, 'furgon', 0, false, true, false, false, 400),
-- Electrodomésticos
('lavadora',    'Lavadora',            '🫧', 'Electrodomésticos', 0.8, 'furgon', 1, true, false, false, false, 410),
('lavaSeca',    'Lavadora-secadora',   '🫧', 'Electrodomésticos', 0.9, 'furgon', 1, true, false, false, false, 420),
('secadora',    'Secadora',            '🌀', 'Electrodomésticos', 0.8, 'furgon', 1, true, false, false, false, 430),
('calefont',    'Calefont / termo',    '🚿', 'Electrodomésticos', 0.4, 'furgon', 0, false, false, false, false, 440),
('estufa',      'Estufa / calefactor', '🔥', 'Electrodomésticos', 0.5, 'furgon', 0, false, false, false, false, 450),
('aire',        'Aire acondicionado',  '🌬️', 'Electrodomésticos', 0.5, 'furgon', 0, false, false, false, false, 460),
('ventilador',  'Ventilador',          '💨', 'Electrodomésticos', 0.3, 'furgon', 0, false, false, false, false, 470),
('aspiradora',  'Aspiradora',          '🧹', 'Electrodomésticos', 0.3, 'furgon', 0, false, false, false, false, 480),
-- Oficina
('escritorio',  'Escritorio',          '💻', 'Oficina', 0.8, 'furgon',   0, false, false, false, false, 490),
('escritorioL', 'Escritorio en L / gamer', '🖥️', 'Oficina', 1.4, 'furgon', 1, true, false, false, false, 500),
('sillaOfic',   'Silla de oficina',    '🪑', 'Oficina', 0.5, 'furgon',   0, false, false, false, false, 510),
('librero',     'Librero / estante',   '📚', 'Oficina', 1.0, 'furgon',   0, false, false, false, true,  520),
('archivador',  'Archivador / kardex', '🗂️', 'Oficina', 0.7, 'furgon',   0, true,  false, false, false, 530),
('pcMonitor',   'PC / monitor (caja)', '🖨️', 'Oficina', 0.2, 'furgon',   0, false, true,  false, false, 540),
('impresora',   'Impresora / multifuncional', '🖨️', 'Oficina', 0.3, 'furgon', 0, false, false, false, false, 550),
('cajaFuerte',  'Caja fuerte',         '🔐', 'Oficina', 0.3, 'furgon',   1, true,  false, false, false, 560),
-- Baño
('vanitorio',   'Lavamanos / vanitorio','🚰', 'Baño', 0.6, 'furgon',   0, false, true,  false, false, 570),
('muebleBano',  'Mueble / repisa de baño', '🧴', 'Baño', 0.5, 'furgon', 0, false, false, false, false, 580),
('espejoBano',  'Espejo de baño',      '🪞', 'Baño', 0.2, 'furgon',   0, false, true,  false, false, 590),
('canastoRopa', 'Canasto de ropa',     '🧺', 'Baño', 0.2, 'furgon',   0, false, false, false, false, 600),
-- Exterior / terraza
('mesaTerraza', 'Mesa de terraza',     '⛱️', 'Exterior', 1.0, 'furgon', 0, false, false, false, false, 610),
('sillasTerraza','Sillas de terraza (set)', '🪑', 'Exterior', 0.8, 'furgon', 0, false, false, false, false, 620),
('quitasol',    'Quitasol / sombrilla','🏖️', 'Exterior', 0.4, 'furgon', 0, false, false, true,  false, 630),
('parrilla',    'Parrilla / quincho',  '🔥', 'Exterior', 0.8, 'furgon', 0, false, false, false, false, 640),
('bodegaJardin','Bodega de jardín',    '🏚️', 'Exterior', 1.5, 'furgon', 1, true,  false, false, false, 650),
('maceteros',   'Maceteros / plantas grandes', '🪴', 'Exterior', 0.3, 'furgon', 0, false, true, false, false, 660),
('cortadora',   'Cortadora de pasto',  '🌱', 'Exterior', 0.4, 'furgon', 0, false, false, false, false, 670),
('escalera',    'Escalera',            '🪜', 'Exterior', 0.4, 'furgon', 0, false, false, true,  false, 680),
('herramientas','Caja de herramientas','🧰', 'Exterior', 0.3, 'furgon', 0, true,  false, false, false, 690),
('bancoTrabajo','Banco de trabajo',    '🔨', 'Exterior', 1.2, 'furgon', 1, true,  false, false, false, 700),
-- Bebé y niños
('cuna',        'Cuna',                '🍼', 'Bebé y niños', 1.2, 'furgon', 0, false, false, false, false, 710),
('practicuna',  'Corral / practicuna', '🧷', 'Bebé y niños', 0.5, 'furgon', 0, false, false, false, false, 720),
('coche',       'Coche / carriola',    '👶', 'Bebé y niños', 0.4, 'furgon', 0, false, false, false, false, 730),
('sillaComer',  'Silla de comer',      '🥣', 'Bebé y niños', 0.3, 'furgon', 0, false, false, false, false, 740),
('sillaAuto',   'Silla de auto',       '🚗', 'Bebé y niños', 0.3, 'furgon', 0, false, false, false, false, 750),
('juguetes',    'Caja de juguetes',    '🧸', 'Bebé y niños', 0.2, 'furgon', 0, false, false, false, false, 760),
('juegoJardin', 'Resbalín / juegos',   '🛝', 'Bebé y niños', 0.9, 'furgon', 0, false, false, false, false, 770),
-- Deco y varios
('cuadros',     'Cuadros / espejos (set)', '🖼️', 'Deco y varios', 0.3, 'furgon', 0, false, true, false, false, 780),
('plantas',     'Plantas de interior', '🪴', 'Deco y varios', 0.2, 'furgon', 0, false, true,  false, false, 790),
('maletas',     'Maletas / bolsos',    '🧳', 'Deco y varios', 0.3, 'furgon', 0, false, false, false, false, 800),
('ropaBolsas',  'Bolsas de ropa',      '👕', 'Deco y varios', 0.2, 'furgon', 0, false, false, false, false, 810),
('bicicleta',   'Bicicleta',           '🚲', 'Deco y varios', 0.5, 'furgon', 0, false, false, true,  false, 820),
('trotadora',   'Trotadora / caminadora', '🏃', 'Deco y varios', 1.2, 'camion34', 1, true, false, false, false, 830),
('biciEstatica','Bicicleta estática / spinning', '🚴', 'Deco y varios', 0.6, 'furgon', 1, true, false, false, false, 840),
('pesas',       'Set de pesas / mancuernas', '🏋️', 'Deco y varios', 0.3, 'furgon', 1, true, false, false, false, 850),
('pianoVert',   'Piano vertical',      '🎹', 'Deco y varios', 2.5, 'camion34', 2, true, false, false, false, 860),
('tecladoDig',  'Piano digital / teclado', '🎹', 'Deco y varios', 0.4, 'furgon', 0, false, false, false, false, 870),
('instrumento', 'Instrumento (guitarra, batería…)', '🎸', 'Deco y varios', 0.3, 'furgon', 0, false, true, false, false, 880),
('acuario',     'Acuario / pecera',    '🐠', 'Deco y varios', 0.3, 'furgon', 0, false, true,  false, false, 890),
('jaulaMascota','Jaula / casa de mascota', '🐾', 'Deco y varios', 0.4, 'furgon', 0, false, false, false, false, 900),
('moto',        'Moto / scooter',      '🏍️', 'Deco y varios', 1.0, 'furgon', 1, true, false, false, false, 910),
-- Cajas
('cajaP',       'Caja pequeña',        '📦', 'Cajas', 0.08, 'furgon', 0, false, false, false, false, 920),
('cajaM',       'Caja mediana',        '📦', 'Cajas', 0.18, 'furgon', 0, false, false, false, false, 930),
('cajaG',       'Caja grande',         '📦', 'Cajas', 0.35, 'furgon', 0, false, false, false, false, 940),
('cajaLibros',  'Caja de libros',      '📦', 'Cajas', 0.15, 'furgon', 0, true,  false, false, false, 950),
('cajaRopa',    'Caja de ropa / vestuario', '📦', 'Cajas', 0.20, 'furgon', 0, false, false, false, false, 960),
('bolsaEmb',    'Bolso de embalaje',   '🛍️', 'Cajas', 0.12, 'furgon', 0, false, false, false, false, 970)
on conflict (item_key) do update set
  name = excluded.name,
  icon = excluded.icon,
  category = excluded.category,
  volume_m3 = excluded.volume_m3,
  min_vehicle_type = excluded.min_vehicle_type,
  required_helpers = excluded.required_helpers,
  is_heavy = excluded.is_heavy,
  is_fragile = excluded.is_fragile,
  is_long = excluded.is_long,
  is_tall = excluded.is_tall,
  sort_order = excluded.sort_order,
  updated_at = now();
