[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["cd server && npm install"]

[phases.build]
cmds = ["cd client && npm install --include=dev && npm run build"]

[start]
cmd = "NODE_ENV=production node --dns-result-order=ipv4first server/index.js"
